### PR TITLE
feat: upgrade chrome version

### PR DESCRIPTION
**Pull request by xoxwgys56**
- serverless-chrome v1.0.0-37 to v1.0.0-55
- chromedriver 2.37 to 2.43

also applied changed version on README and add chromium binary version

### CODE REVIEW

**Comment by umihico** [comment]
@xoxwgys56 
Thank you! I created a new release.
https://github.com/umihico/docker-selenium-lambda/releases/tag/v5

**Comment by umihico** [comment]
@xoxwgys56 
After I merged yours, I didn't find your name as a contributor. It is might be because your commit is created by `dwkim` which is your local git config. This link might solve the situation.

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/adding-an-email-address-to-your-github-account
https://docs.github.com/en/github/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user

**Comment by xoxwgys56** [comment]
@umihico Thanks I checked and add `dwkim`. but It is not applied as contributor so sad..

**Comment by umihico** [comment]
@xoxwgys56 
Yeah your commit has now your profile pic. I don’t get why. Maybe past stuff are not recalculated? Sorry

**Comment by xoxwgys56** [comment]
@umihico Yes it is. After time I try another contribute. :)

**Pull request merged**
