### PR TITLE
Using new Service object instead of deprecated execution_path

### PR DESCRIPTION
**Pull request by filipopo**
In selenium 4.9.1 which this repo is using at the moment, a message pops up about execution_path being deprecated: DeprecationWarning: executable_path has been deprecated, please pass in a Service object

In newer versions of selenium this code doesn't work at all so it should be changed to using the new syntax

### CODE REVIEW

**Review by umihico — APPROVED** [review]
Worked perfectly. Thank you!

**Comment by filipopo** [comment]
I think you must bump the selenium version now to 4.11.0 at least😅, 4.11.2 is the latest

**Comment by filipopo** [comment]
May I ask is there something keeping you from upgrading the selenium version? in my tests this syntax works on >=4.11.0

**Comment by umihico** [comment]
@filipopo 
It was because https://github.com/umihico/docker-selenium-lambda/pull/175, and just now I realized you are fixing this!

So I created #192.
Thank you again.

**Pull request merged**
